{% set name = "sasl" %}
{% set version = "0.3a1" %}
{% set sha256 = "a513d2536b8a65a9301d4091384a1e7ee5512d64cd5fc26001535dde5940ad5a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/cloudera/python-sasl/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - cyrus-sasl
    - cython
  run:
    - python
    - cyrus-sasl
    - six

test:
  imports:
    - sasl

about:
  home: http://github.com/cloudera/python-sasl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Python wrapper for Cyrus SASL'
  dev_url: http://github.com/cloudera/python-sasl

extra:
  recipe-maintainers:
    - mariusvniekerk
    - wesm
    - martindurant
