# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "FPMamJTXJMcC+VTnt525uH9mCwZIeLN8gc4N61m9em835RpTKPG3FC2SUnxPtfHOPq/cT1TFou1x22XUaBwYGGw0UqCkAiaER8ETveouWCF/oB2sEESmimheqjOnOwvvcigUKgV6BIhJLd4z6tZuC8n/3C1NUd35ids1pW4P/JM2dAEVwScGwRglaf7kxol/iOQvLyk3StT5DoV7sVF/mmgB7OFnEpEdq2HCVPcdwV17OXs8QNXF3q9msVHE5Qf5vpSXF1MyZVd9qW4lgtUAxKmAHyszXBYUdCg6JRDw1eHAGvP9jQr0cR5kodNtJ84ks5zf+gSqmtyDs0K1te+kFBCsqDMrY1xiWlVCouUDeQzQ+XeNVRkFZBfWY+UAXdIvP+XYshGjhgTTjskRpgwyfyi7da/ihlin6hsrZUD9z/LSnPkJUIObVvq8lPTTwoM6IE64b2swzUVxcwmOxXAotd/yTX5MiRi4ElODygacKKXZdlJ8WltUPgOPtxuhQhS4esxATxjQM7ggIGiwH0ZLF4bbtznI09sJo0wO/YalYilMEXzT9t4IACbAPajjhOydSEmWdeqCR1MGCjGbUIe3iAosHRU2rCRixGK5uvoEjClCbxwTkE1g80bwiw5S8LY2yuVLmDhGnqun9elG94yxaH6HWT15lp68oolzgoCA2jk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
