appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: H5A0VaqeSsCiZQHrnD73FLSwRcKOaPrG3duvPxYMBC9/s7hKor+OGWgf+TmAw1VWGMbrZWoqRFuhuHpkbQzxOoM/LcRGuzFk+tOpqHohIN1DXvqv66/Rc/F6LqyY9VfD+zUsj8CN+jmJUpZ2M5tnbjapP448MT7OMS69u9+OsaMQnMsgumUObRreyMTXO/Fiq0NZUjd/4Ej8r0gYyDWecSeY+3Z84/4AduqUBlQSgmkhaDEJEXOgotfwMXaGR15FpmXVTf8DgMqQZE0g3vCSjCAHtD7d7LtLLbAMFhEz3EemQnFnj9n8+vIGvk/3F6G79BVGjqqPmXa9DeR76wemqAsDpR33Ib3R7mgJwUKUX6TwXR8HYs1nHgpU5qFIWVeqODhml6KCeTntk8yITzkUelgHT62upVn9E3GrMoQwYr7+LLxM9hm/GeJ53mE9AYmU2plVQkv/VIfJsxvUwJVz0YAYn7YVfILCcZaf//QWfIThzNI1StAsRbCcrM/jw9vPw2k5Satq+WOwLMnxIqUI4hejiDOCeJAyqLuBDENohyvEratWTXvfAStlf/IF/iZBMEYKAN5hkaK5lQTn5VafKrLgBTaw+ay7ycXs1aavJjAfld/NiWAh/ky72oU/ZtOEVmy+oYj2VaH0878/lDfCdugjD6Un5d1QPKGAOIe+ekE=}
